// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OcelotAdmin.Data;

#nullable disable

namespace OcelotAdmin.Migrations
{
    [DbContext(typeof(OcelotAdminDbContext))]
    [Migration("20260811192233_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("OcelotAdmin.Domain.ConfigurationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GatewayId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GatewayId", "PublishedAt");

                    b.ToTable("ConfigurationHistory");
                });

            modelBuilder.Entity("OcelotAdmin.Domain.ConsulGatewaySettings", b =>
                {
                    b.Property<Guid>("GatewayId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationKey")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.HasKey("GatewayId");

                    b.ToTable("ConsulGatewaySettings");
                });

            modelBuilder.Entity("OcelotAdmin.Domain.FileGatewaySettings", b =>
                {
                    b.Property<Guid>("GatewayId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationPath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("GatewayId");

                    b.ToTable("FileGatewaySettings");
                });

            modelBuilder.Entity("OcelotAdmin.Domain.Gateway", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfigStoreType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Gateways");
                });

            modelBuilder.Entity("OcelotAdmin.Domain.GatewayDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GatewayId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GatewayId")
                        .IsUnique();

                    b.ToTable("GatewayDrafts");
                });

            modelBuilder.Entity("OcelotAdmin.Domain.ConfigurationHistory", b =>
                {
                    b.HasOne("OcelotAdmin.Domain.Gateway", "Gateway")
                        .WithMany("ConfigurationHistory")
                        .HasForeignKey("GatewayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gateway");
                });

            modelBuilder.Entity("OcelotAdmin.Domain.ConsulGatewaySettings", b =>
                {
                    b.HasOne("OcelotAdmin.Domain.Gateway", "Gateway")
                        .WithOne("ConsulSettings")
                        .HasForeignKey("OcelotAdmin.Domain.ConsulGatewaySettings", "GatewayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gateway");
                });

            modelBuilder.Entity("OcelotAdmin.Domain.FileGatewaySettings", b =>
                {
                    b.HasOne("OcelotAdmin.Domain.Gateway", "Gateway")
                        .WithOne("FileSettings")
                        .HasForeignKey("OcelotAdmin.Domain.FileGatewaySettings", "GatewayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gateway");
                });

            modelBuilder.Entity("OcelotAdmin.Domain.GatewayDraft", b =>
                {
                    b.HasOne("OcelotAdmin.Domain.Gateway", "Gateway")
                        .WithOne("Draft")
                        .HasForeignKey("OcelotAdmin.Domain.GatewayDraft", "GatewayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gateway");
                });

            modelBuilder.Entity("OcelotAdmin.Domain.Gateway", b =>
                {
                    b.Navigation("ConfigurationHistory");

                    b.Navigation("ConsulSettings");

                    b.Navigation("Draft");

                    b.Navigation("FileSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
